clc;
a=imread("C:\Program Files\scilab-6.1.1\IPCV\images\checkerbox.png")
a=rgb2gray(a)
e1=edge(a,'sobel')
e2=edge(a,'prewitt')
e3=edge(a,'canny')
subplot(2,2,1);imshow(a)
subplot(2,2,2);imshow(e1)
subplot(2,2,3);imshow(e2)
subplot(2,2,4);imshow(e3)
